spring.application.name=indusync
spring.datasource.url=jdbc:mysql://localhost:3306/indusync_db
spring.datasource.username=indusync
spring.datasource.password=Indusync@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
